### ISSUE TITLE
/.zshrc:source:101: no such file or directory: usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

### ISSUE THREAD

**Issue by JuanCarvalho** [snkshukla/docker-alpine-zsh#1]
The line "RUN usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" is whitout '/' in usr
this cause a lite error. 

Correct  "/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" 

Thanks for your code ;)

**Comment by snkshukla** [comment]
@JuanCarvalho Thank you for pointing out the issue, missed that one somehow, I guess I didn't test it. :)
